# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
# Default hooks generally useful
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
# Secret Scanning Hook to prevents committing sensitive credentials or secrets
# NOTE: VERSION OF PACKAGES SHOULD NOT BE UPGRADED WITHOUT A VULNERABILITY SCAN. GET YOUR SPOC TO DO IT.
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
    -   id: gitleaks
        args: ['--config=pyproject.toml']
# Scanning and fixing automatically unused imports
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        # Exclude init files avoid unexpected rewrite behaviour when __all__
        # is not defined in the file
        args: [--remove-all-unused-imports, --in-place, --exclude, "**/__init__.py"]
# hook for auto-formatting, copyright notice check and type checking - security currently not enabled
-   repo: local
    hooks:
        -   id: black-formatting-hook
            name: Run autoformatting black
            entry: bash -xc 'black --config ./pyproject.toml -- "$@"' --
            language: system
            types_or: [python]
            # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
            # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
            verbose: true
        -   id: isort-formatting-hook
            name: Run autoformatting isort
            entry: bash -xc 'isort --settings-path ./pyproject.toml -- "$@"' --
            language: system
            types_or: [python]
            # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
            # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
            verbose: true
        -   id: flake8-linter-hook-copyright
            name: Run Flake8 linter to check for the copyright
            entry: bash -xc 'flake8 --select C801 --copyright-check --copyright-regexp="# Copyright \u00A9 [0-9]{4}(, [0-9]{4})* Oracle and/or its affiliates.\n#\n# This software is under the Universal Permissive License\n# \(UPL\) 1.0 \(LICENSE-UPL or https://oss.oracle.com/licenses/upl\) or Apache License\n# 2.0 \(LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0\), at your option." -- "$@"' --
            language: system
            types_or: [python]
            # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
            # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
            verbose: true
        -   id: type-checking-hook
            name: Run type checking (mypy)
            entry: bash -xc './.venv-wayflowcore/bin/mypy -- "$@"' --
            language: system
            types_or: [python]
            # We exclude the fuzz tests from this check
            exclude: '.?tests_fuzz/.'
            # 'verbose:' when set to true, makes the pre-commit framework itself verbose. This means more detailed logging
            # about what the pre-commit framework is doing, not just the hook. Useful for debugging or understanding the hook's behavior.
            verbose: true
        -   id: bandit-security-hook
            name: Run bandit security checks
            entry: bandit -c pyproject.toml --exclude **/tests/** --
            language: system
            types_or: [ python ]
