# Copyright © 2025 Oracle and/or its affiliates.
#
# This software is under the Universal Permissive License
# (UPL) 1.0 (LICENSE-UPL or https://oss.oracle.com/licenses/upl) or Apache License
# 2.0 (LICENSE-APACHE or http://www.apache.org/licenses/LICENSE-2.0), at your option.

from wayflowcore.serialization.serializer import SerializableObject, _import_all_submodules

_import_all_submodules("wayflowcore")


ALL_SERIALIZABLE_CLASSES = {
    "Agent",
    "AgentConversation",
    "AgentConversationExecutionState",
    "Component",
    "ContextProvider",
    "ControlFlowEdge",
    "Conversation",
    "DataFlowEdge",
    "DescribedAgent",
    "DescribedFlow",
    "EmbeddingModel",
    "OpenAICompatibleEmbeddingModel",
    "OpenAIEmbeddingModel",
    "OracleDatabaseConnectionConfig",
    "OracleDatabaseDatastore",
    "OCIGenAIEmbeddingModel",
    "OllamaEmbeddingModel",
    "VllmEmbeddingModel",
    "Entity",
    "Event",
    "ExecutionInterrupt",
    "ExecutionStatus",
    "FinishedStatus",
    "Flow",
    "FlowConversation",
    "FlowConversationExecutionState",
    "InMemoryDatastore",
    "InterruptedExecutionStatus",
    "JsonToolOutputParser",
    "LlmModel",
    "MTlsOracleDatabaseConnectionConfig",
    "Message",
    "MessageList",
    "OciAgent",
    "OciAgentConversation",
    "OciAgentState",
    "PromptTemplate",
    "Property",
    "PythonToolOutputParser",
    "ReactToolOutputParser",
    "RegexOutputParser",
    "RegexPattern",
    "SoftTimeoutExecutionInterrupt",
    "SoftTokenLimitExecutionInterrupt",
    "Step",
    "Swarm",
    "SwarmUser",
    "SwarmConversation",
    "SwarmConversationExecutionState",
    "SwarmJsonToolOutputParser",
    "SwarmThread",
    "TlsOracleDatabaseConnectionConfig",
    "Tool",
    "ToolRequestStatus",
    "UserMessageRequestStatus",
    "Variable",
    "TextContent",
    "ImageContent",
    "MessageContent",
    "AppendTrailingSystemMessageToUserMessageTransform",
    "_ToolRequestAndCallsTransform",
    "CoalesceSystemMessagesTransform",
    "RemoveEmptyNonUserMessageTransform",
    "_PythonMergeToolRequestAndCallsTransform",
    "_LlamaMergeToolRequestAndCallsTransform",
    "_ReactMergeToolRequestAndCallsTransform",
    "_TokenConsumptionEvent",
    "SSETransport",
    "MCPToolBox",
    "MCPTool",
    "JsonOutputParser",
    "LlmGenerationConfig",
    "LlmCompletion",
    "Prompt",
    "TokenUsage",
    "RemoteTool",
    "StdioTransport",
    "SSEmTLSTransport",
    "StreamableHTTPmTLSTransport",
    "SessionParameters",
    "StreamableHTTPTransport",
    "StepDescription",
    "OutputParser",
    "MessageTransform",
    "ClientTransport",
    "SerializableDataclass",
    "FrozenSerializableDataclass",
    "ToolRequest",
    "ToolResult",
    "ToolOutputParser",
    "OCIClientConfig",
    "HTTPmTLSBaseTransport",
    "ManagerWorkersConversation",
    "ManagerWorkersConversationExecutionState",
    "ManagerWorkers",
    "ManagerWorkersJsonToolOutputParser",
}


def test_componentregistry():
    component_registry = SerializableObject._COMPONENT_REGISTRY
    assert set(component_registry) == ALL_SERIALIZABLE_CLASSES
