[build-system]
requires = [
    "setuptools<72.0.0",
    "wheel",
    # setuptools-scm lets us include all necessary files (e.g. .pyx files) in the source
    # distribution (sdist) without needing a MANIFEST.in file.
    "setuptools-scm == 7.1.0",
]
build-backend = "setuptools.build_meta"
